### ISSUE TITLE
How does the magic velocity section in `arcadeFlightModel.ts` work?

### ISSUE THREAD

**Issue by roombawulf** [ruben3d/retroflightsim#27]
Hi @ruben3d,

I'm working on my own arcade flight game in three and hope you could help me understand the way you apply velocity to your plane model.

Currently I'm getting my plane object's world direction via the `Object3D.getWorldDirection()`. Then I just apply a hard coded speed scalar value to that and add it the position of my plane.

You seem to hardcode a forward direction and then do some quaternion math to rotate your plane. Is there a benefit to that method?

**Comment by ruben3d** [comment]
@roombawulf Basically we are doing the same thing. Starting with the phisically correct formula, I implemented a few changes and simplifications to achieve the kind of arcade behaviour I was looking for. I try to keep a few bits with the realistic formulas and constants because it is easier to fine tune and understand what is going on.

So the forces applied to your plane are Lift, Thrust, Drag and Weight. From Newton we know that $\vec F = m \vec a$, so this is the Thrust force:
```
roundToZero(this.thrust.copy(this.forward).multiplyScalar(
            thrustDensity *
            MAX_THRUST *
            this.effectiveThrottle *
            DRY_MASS));
```
which is basically the forward vector times the engine thrust times mass.

Later we resolve for acceleration, $\vec a = \vec F / m$, and apply the acceleration to the current velocity vector times the timestep delta, from this basic velocity equation $\vec v = \vec v_0 + \vec a t$ :
```
const accel = roundToZero(this.forces.add(this.friction).divideScalar(DRY_MASS));
this.velocity.addScaledVector(accel, delta);
```
And lastly, we update the plane position in the same way you are doind it already, $\vec p = \vec p_0 + \vec v t$ :
```
this.obj.position.addScaledVector(roundToZero(this.velocity, this.effectiveThrottle > 0 ? 0.01 : 0.1), delta);
```
The _magic velocity rotation_ is trying to approach how a plane turns when rolling. In the real world the lift force is the one inducing the turn and requires pulling the control stick to avoid losing altitude, but I'm not modeling this in a realistic way anyway.  (Very) old flight sims kept level flight when rolling, and just increased the risk of stalling.

**Comment by roombawulf** [comment]
Ah okay, so the _magic velocity rotation_ is for handling turning when rolling. I would definitely like to implement that into my version. I've got very barebones controls at the moment. Thanks for the detailed response. I am going to close the thread... unless you have anything else to add 👍 

Edit: I guess my only other question is why you choose to use hardcoded direction vectors, as opposed to using `getWorldDirection()` for example.

**Comment by ruben3d** [comment]
> I guess my only other question is why you choose to use hardcoded direction vectors, as opposed to using getWorldDirection() for example.

For consistency. As you said, three.js provides the handy `getWorldDirection()` in its `Object3D` class for the Forward vector (+Z). But what happens if you aren't using an `Object3D`? That method isn't available. Or what about the Up (+Y) and Right (+X) directions? You have to calculate them yourself. So in the end finding the Forward vector for an `Object3D` felt like a special case, and I made the decision to unify all of them to look the same, so the code is easier to read.
